// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmghpkoumxqbuwebkjxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tZ2hwa291bXhxYnV3ZWJranhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1OTMxNjAsImV4cCI6MjA3MzE2OTE2MH0.-BUg9T_PsTXCGalZEp1ozwgVaGJ0uCXrMnShbi-84c0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});